### ISSUE TITLE
알림나무 API 

### ISSUE THREAD

**Issue by kang-jisu** [YAPP-Github/20th-Web-Team-1-BE#26]
### 목적
> 매일 갱신되는 8개의 칭찬메시지가 생성되는 알림나무 API를 구현한다. 

### 개발 내용 정리 -> 잘못적은 부분 수정 필요 
- [x] 비트리가 제공하는 기본 명언, 칭찬메시지는 Enum이나 전역 값으로 최소 8개 만들어둔다. -> 일단 메시지 id를 음수로 해서 디비에서 말고 하드코딩된 코드안에서 가져오도록 함.
- [x] 안읽은 메시지 , 즐겨찾기한 메시지, 비트리 제공 메시지 로 알림나무 열매 8개를 만든다.
  - 먼저 안읽은 메시지가 8개 이상이면 그중에 8개를 뽑는다.
  - 안읽은 메시지가 8개 이하이면 즐겨찾기한 메시지로 (안읽은메시지 + 즐겨찾기 메시지 ) 8개를 채운다.
  -  그래도 8개가 안되면 비트리 제공 메시지로 8개를 만든다.
  - 배치 적용하기 전에는 수동 갱신 API를 만들어서 유저마다 알림나무 열매를 새로 만들어 DB에 메시지 id 8개 리스트를 저장한다. 

NoticeTree Entity
- [x] 메시지 읽으면 unreadMessage -> readMessages로 이동 필요 
- [x] unreadMessages, readMessages에는 messageId를 ","로 구분한 String 값이 들어감 (1,2,3,4,5,6)(7,8)
- [x] userId 저장 

### 참고 사항
- 알림나무 읽지않은 메시지 개수  -> 전체 메시지 or 8개 뭐였는지? -> 전체메시지
- 알림나무페이지에서 안읽고 메시지함으로 읽어버리면 알림나무에는 읽음처리되는지 아닌지 ?  -> 읽음처리됨

알림나무용 DB 테이블 생성 -> 메시지 id가 8개 들어감 (8개보다 적거나 많을 수 없음)
읽은 메시지 id 처리하는 필드 필요.

**Comment by kang-jisu** [comment]
List -> Set으로 변경하고 즐겨찾기한 메시지 추가 -> 안읽어서 이미 선택된 메시지중에 즐겨찾기 메시지 포함되는거 있을수도 있음 ,중복처리

**Comment by kang-jisu** [comment]
메시지읽음 그냥 post하는건어떤지?

**Comment by suubinkim** [comment]
> 메시지읽음 그냥 post하는건어떤지?

메서드 put말고 post 말씀하시는 건가요?! 알림나무 생성 로직도 포함되어있어서 그러시는건가요?? 어떤 차이예요?

**Comment by kang-jisu** [comment]
> > 메시지읽음 그냥 post하는건어떤지?
> 
> 메서드 put말고 post 말씀하시는 건가요?! 알림나무 생성 로직도 포함되어있어서 그러시는건가요?? 어떤 차이예요?

아 이거는 그냥 무시하셔여!! 그냥 슬쩍든생각인데 나중에봤을때도 고민해보려고 잠깐 메모처럼 남겨뒀어요,, 일단 다른 메시지 필드수정api도 다 put으로 하셨어서 그대로 해도 괜찮을거같아요 그냥 저는 단순히 put이라는거를 쓸만큼의 수정,덮어쓰긴가 ..? 그냥 적당한 조회,삭제 이외의 요청은 다 post로하는건 어떨까 이런저런생각했는데 그냥 진짜 취향인거같아서 넘어가셔도돼욥!!
