### ISSUE TITLE
[fix] 읽음 여부 API 응답 값 변경

### ISSUE THREAD

**Issue by suubinkim** [YAPP-Github/20th-Web-Team-1-BE#89]
### 목적
>  알림나무 페이지에서 언리드 메시지 개수 처리를 위한 읽음 여부 응답 값 변경
### 작업 내용
- [x] 이미 읽은건데 재 요청시 false, 처음 읽음 처리 된 거면 true 리턴 (204 no content ->  200 true/false)
### 참고 사항
-

**Comment by kang-jisu** [comment]
alreadyRead라서 이미읽은거일때 true가맞을거같아요
